In [1]:
import yfinance as yf
import pandas as pd
import time
import tqdm
import json
pd.options.display.float_format = "{:,.0f}".format

In [2]:
url = "https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/nyse/nyse_full_tickers.json"
df_nyse = pd.read_json(url)
url_nasdaq = "https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/refs/heads/main/nasdaq/nasdaq_full_tickers.json"
df_nasdaq = pd.read_json(url_nasdaq)

df_raw = pd.concat([df_nyse, df_nasdaq], ignore_index=True)

# Remove symbols with '^' character
df_raw = df_raw[df_raw["symbol"].str.contains(r"\^") == False]

# Ensure market cap is numeric. Drop NA
df_raw["marketCap"] = pd.to_numeric(df_raw["marketCap"], errors='coerce')
df_raw["symbol"] = df_raw["symbol"].str.replace("/", "-", regex=False)
df_raw.dropna(subset=["marketCap"], inplace=True)
df_raw = df_raw[df_raw.marketCap > 10000000]

accepted_countries = set(['United States', 'Canada', 'United Kingdom', 'Germany', 'France', 'Italy', 'Spain', 'Netherlands', 'Switzerland', 'Australia', 'Japan', 'Kazakhstan', 'Ireland', 'Sweden', 'Denmark', 'Norway', 'Finland'])
df_raw = df_raw[df_raw.country.isin(accepted_countries)]

df = df_raw[['symbol', 'name', 'marketCap', 'country', 'ipoyear', 'industry', 'sector']].copy()
df.head(3)

,symbol,name,marketCap,country,ipoyear,industry,sector
0,A,Agilent Technologies Inc. Common Stock,"36,650,360,162",United States,1999,Biotechnology: Laboratory Analytical Instruments,Industrials
1,AA,Alcoa Corporation Common Stock,"15,320,312,133",United States,2016,Aluminum,Industrials
2,AAMI,Acadian Asset Management Inc. Common Stock,"1,820,450,938",United Kingdom,2014,Investment Managers,Finance

In [3]:
df[df.symbol.str.contains(r"BRK")]

,symbol,name,marketCap,country,ipoyear,industry,sector
421,BRK-A,Berkshire Hathaway Inc.,"1,121,643,841,957",United States,,,
422,BRK-B,Berkshire Hathaway Inc.,"1,121,004,744,491",United States,,,
2037,RBRK,Rubrik Inc. Class A Common Stock,"10,221,228,703",United States,2024,Computer Software: Prepackaged Software,Technology
3303,BRKR,Bruker Corporation Common Stock,"6,370,892,168",United States,,Biotechnology: Laboratory Analytical Instruments,Industrials
3304,BRKRP,Bruker Corporation 6.375% Mandatory Convertibl...,"50,357,093,650",United States,,Biotechnology: Laboratory Analytical Instruments,Industrials

In [4]:
dats = yf.Tickers(df.symbol.to_list())

In [6]:
company = yf.Ticker("TSLA")

In [8]:
company.financials

,2025-12-31,2024-12-31,2023-12-31,2022-12-31,2021-12-31
Tax Effect Of Unusual Items,"-133,380,000","-136,800,000",0,"-14,080,000",NaN
Tax Rate For Calcs,0,0,0,0,NaN
Normalized EBITDA,"12,258,000,000","15,392,000,000","14,796,000,000","17,833,000,000",NaN
Total Unusual Items,"-494,000,000","-684,000,000",0,"-176,000,000",NaN
Total Unusual Items Excluding Goodwill,"-494,000,000","-684,000,000",0,"-176,000,000",NaN
Net Income From Continuing Operation Net Minority Interest,"3,794,000,000","7,130,000,000","14,999,000,000","12,583,000,000",NaN
Reconciled Depreciation,"6,148,000,000","5,368,000,000","4,667,000,000","3,747,000,000",NaN
Reconciled Cost Of Revenue,"77,733,000,000","80,240,000,000","79,113,000,000","60,609,000,000",NaN
EBITDA,"11,764,000,000","14,708,000,000","14,796,000,000","17,657,000,000",NaN
EBIT,"5,616,000,000","9,340,000,000","10,129,000,000","13,910,000,000",NaN
Net Interest Income,"1,342,000,000","1,219,000,000","910,000,000","106,000,000",NaN
Interest Expense,"338,000,000","350,000,000","156,000,000","191,000,000",NaN
Interest Income,"1,680,000,000","1,569,000,000","1,066,000,000","297,000,000",NaN
Normalized Income,"4,154,620,000","7,677,200,000","14,999,000,000","12,744,920,000",NaN
Net Income From Continuing And Discontinued Operation,"3,794,000,000","7,130,000,000","14,999,000,000","12,583,000,000",NaN
Total Expenses,"89,978,000,000","89,930,000,000","87,882,000,000","67,630,000,000",NaN
Rent Expense Supplemental,NaN,"1,003,000,000","1,268,000,000","1,509,000,000","978,000,000"
Total Operating Income As Reported,"4,355,000,000","7,076,000,000","8,891,000,000","13,656,000,000",NaN
Diluted Average Shares,"3,526,250,000","3,216,000,000","3,482,750,000","3,475,000,000",NaN
Basic Average Shares,"3,224,750,000","3,216,000,000","3,173,500,000","3,130,000,000",NaN
Diluted EPS,1,2,4,4,NaN
Basic EPS,1,2,5,4,NaN
Diluted NI Availto Com Stockholders,"3,794,000,000","7,130,000,000","14,999,000,000","12,584,000,000",NaN
Average Dilution Earnings,NaN,0,0,"1,000,000","9,000,000"
Net Income Common Stockholders,"3,794,000,000","7,130,000,000","14,999,000,000","12,583,000,000",NaN
Otherunder Preferred Stock Dividend,NaN,NaN,NaN,NaN,"-5,000,000"
Net Income,"3,794,000,000","7,130,000,000","14,999,000,000","12,583,000,000",NaN
Minority Interests,"-61,000,000","-23,000,000","25,000,000","-4,000,000",NaN
Net Income Including Noncontrolling Interests,"3,855,000,000","7,153,000,000","14,974,000,000","12,587,000,000",NaN
Net Income Continuous Operations,"3,855,000,000","7,153,000,000","14,974,000,000","12,587,000,000",NaN
Tax Provision,"1,423,000,000","1,837,000,000","-5,001,000,000","1,132,000,000",NaN
Pretax Income,"5,278,000,000","8,990,000,000","9,973,000,000","13,719,000,000",NaN
Other Income Expense,"-913,000,000","11,000,000","172,000,000","-219,000,000",NaN
Other Non Operating Income Expenses,"-419,000,000","695,000,000","172,000,000","-43,000,000",NaN
Special Income Charges,"-494,000,000","-684,000,000",0,"-176,000,000",NaN
Restructuring And Mergern Acquisition,"494,000,000","684,000,000",0,"176,000,000",NaN
Net Non Operating Interest Income Expense,"1,342,000,000","1,219,000,000","910,000,000","106,000,000",NaN
Interest Expense Non Operating,"338,000,000","350,000,000","156,000,000","191,000,000",NaN
Interest Income Non Operating,"1,680,000,000","1,569,000,000","1,066,000,000","297,000,000",NaN
Operating Income,"4,849,000,000","7,760,000,000","8,891,000,000","13,832,000,000",NaN
Operating Expense,"12,245,000,000","9,690,000,000","8,769,000,000","7,021,000,000",NaN
Research And Development,"6,411,000,000","4,540,000,000","3,969,000,000","3,075,000,000",NaN
Selling General And Administration,"5,834,000,000","5,150,000,000","4,800,000,000","3,946,000,000",NaN
Gross Profit,"17,094,000,000","17,450,000,000","17,660,000,000","20,853,000,000",NaN
Cost Of Revenue,"77,733,000,000","80,240,000,000","79,113,000,000","60,609,000,000",NaN
Total Revenue,"94,827,000,000","97,690,000,000","96,773,000,000","81,462,000,000",NaN
Operating Revenue,"94,827,000,000","97,690,000,000","96,773,000,000","81,462,000,000",NaN

In [ ]:
company.

In [ ]:
all_info = []
with open("company_info.json", "a") as f:
    for symbol in tqdm.tqdm(df.symbol.to_list()):
        try:
            info = dats.tickers[symbol].info
            all_info.append(info)
            f.write(json.dumps(info) + "\n")
            time.sleep(0.2)  # To avoid hitting rate limits
        except Exception as e:
            # f.write(f"{symbol}: ERROR - {str(e)}\n")
            # time.sleep(0.2)  # To avoid hitting rate limits
            print(symbol, "ERROR:", str(e))

# json.dump(all_info, open("company_info.json", "w"), indent=4)

 13%|█▎        | 553/4397 [04:48<33:22,  1.92it/s]

KeyboardInterrupt: