In [11]:
import yfinance as yf
ticker = yf.Ticker("AAPL")
info = ticker.info

In [16]:
info.keys()

dict_keys(['address1', 'city', 'state', 'zip', 'country', 'phone', 'website', 'industry', 'industryKey', 'industryDisp', 'sector', 'sectorKey', 'sectorDisp', 'longBusinessSummary', 'fullTimeEmployees', 'companyOfficers', 'auditRisk', 'boardRisk', 'compensationRisk', 'shareHolderRightsRisk', 'overallRisk', 'governanceEpochDate', 'compensationAsOfEpochDate', 'irWebsite', 'executiveTeam', 'maxAge', 'priceHint', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'dividendRate', 'dividendYield', 'exDividendDate', 'payoutRatio', 'fiveYearAvgDividendYield', 'beta', 'trailingPE', 'forwardPE', 'volume', 'regularMarketVolume', 'averageVolume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask', 'bidSize', 'askSize', 'marketCap', 'nonDilutedMarketCap', 'fiftyTwoWeekLow', 'fiftyTwoWeekHigh', 'allTimeHigh', 'allTimeLow', 'priceToSalesTrailing12Months', 'fiftyDayAverage', 'twoHundredDayAverage', 'trailingAnnualDividendRate', 'trailingAnnualDividendYield', 'currency', 'tradeable', 'enterpriseValue', 'profitMargins', 'floatShares', 'sharesOutstanding', 'sharesShort', 'sharesShortPriorMonth', 'sharesShortPreviousMonthDate', 'dateShortInterest', 'sharesPercentSharesOut', 'heldPercentInsiders', 'heldPercentInstitutions', 'shortRatio', 'shortPercentOfFloat', 'impliedSharesOutstanding', 'bookValue', 'priceToBook', 'lastFiscalYearEnd', 'nextFiscalYearEnd', 'mostRecentQuarter', 'earningsQuarterlyGrowth', 'netIncomeToCommon', 'trailingEps', 'forwardEps', 'pegRatio', 'lastSplitFactor', 'lastSplitDate', 'enterpriseToRevenue', 'enterpriseToEbitda', '52WeekChange', 'SandP52WeekChange', 'lastDividendValue', 'lastDividendDate', 'quoteType', 'currentPrice', 'targetHighPrice', 'targetLowPrice', 'targetMeanPrice', 'targetMedianPrice', 'recommendationMean', 'recommendationKey', 'numberOfAnalystOpinions', 'totalCash', 'totalCashPerShare', 'ebitda', 'totalDebt', 'quickRatio', 'currentRatio', 'totalRevenue', 'debtToEquity', 'revenuePerShare', 'returnOnAssets', 'returnOnEquity', 'grossProfits', 'freeCashflow', 'operatingCashflow', 'earningsGrowth', 'revenueGrowth', 'grossMargins', 'ebitdaMargins', 'operatingMargins', 'financialCurrency', 'symbol', 'language', 'region', 'typeDisp', 'quoteSourceName', 'triggerable', 'customPriceAlertConfidence', 'marketState', 'shortName', 'longName', 'hasPrePostMarketData', 'firstTradeDateMilliseconds', 'postMarketChangePercent', 'postMarketPrice', 'postMarketChange', 'regularMarketChange', 'regularMarketDayRange', 'fullExchangeName', 'averageDailyVolume3Month', 'fiftyTwoWeekLowChange', 'fiftyTwoWeekLowChangePercent', 'fiftyTwoWeekRange', 'fiftyTwoWeekHighChange', 'fiftyTwoWeekHighChangePercent', 'fiftyTwoWeekChangePercent', 'dividendDate', 'earningsTimestamp', 'earningsTimestampStart', 'earningsTimestampEnd', 'earningsCallTimestampStart', 'earningsCallTimestampEnd', 'isEarningsDateEstimate', 'regularMarketChangePercent', 'regularMarketPrice', 'corporateActions', 'postMarketTime', 'regularMarketTime', 'exchange', 'messageBoardId', 'exchangeTimezoneName', 'exchangeTimezoneShortName', 'gmtOffSetMilliseconds', 'market', 'esgPopulated', 'epsTrailingTwelveMonths', 'epsForward', 'epsCurrentYear', 'priceEpsCurrentYear', 'fiftyDayAverageChange', 'fiftyDayAverageChangePercent', 'twoHundredDayAverageChange', 'twoHundredDayAverageChangePercent', 'sourceInterval', 'exchangeDataDelayedBy', 'averageAnalystRating', 'cryptoTradeable', 'displayName', 'trailingPegRatio'])

In [17]:
info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 166000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 55,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1970,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1777593600,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 293.257,
 'open': 291.979,
 'dayLow': 290.23,
 'dayHigh': 293.88,
 'regularMarketPreviousClose': 293.257,
 'regularMarketOpen': 291.979,
 'regularMarketDayLow': 290.23,
 'regularMarketDayHigh': 293.88,
 'dividendRate': 1.08,
 'dividendYield': 0.37,
 'exDividendDate': 1778457600,
 'payoutRatio': 0.1259,
 'fiveYearAvgDividendYield': 0.51,
 'beta': 1.065,
 'trailingPE': 35.390564,
 'forwardPE': 30.615929,
 'volume': 39366022,
 'regularMarketVolume': 39366022,
 'averageVolume': 44422768,
 'averageVolume10days': 53546890,
 'averageDailyVolume10Day': 53546890,
 'bid': 292.64,
 'ask': 293.35,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 4298695245824,
 'nonDilutedMarketCap': 4308095261920,
 'fiftyTwoWeekLow': 193.46,
 'fiftyTwoWeekHigh': 294.76,
 'allTimeHigh': 294.76,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 9.522142,
 'fiftyDayAverage': 262.8026,
 'twoHundredDayAverage': 257.01855,
 'trailingAnnualDividendRate': 1.04,
 'trailingAnnualDividendYield': 0.0035463774,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4324299374592,
 'profitMargins': 0.27152002,
 'floatShares': 14662534368,
 'sharesOutstanding': 14687356000,
 'sharesShort': 134422787,
 'sharesShortPriorMonth': 124192030,
 'sharesShortPreviousMonthDate': 1773360000,
 'dateShortInterest': 1776211200,
 'sharesPercentSharesOut': 0.0092,
 'heldPercentInsiders': 0.01638,
 'heldPercentInstitutions': 0.67577004,
 'shortRatio': 3.24,
 'shortPercentOfFloat': 0.0092,
 'impliedSharesOutstanding': 14687356000,
 'bookValue': 7.26,
 'priceToBook': 40.31405,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1774656000,
 'earningsQuarterlyGrowth': 0.194,
 'netIncomeToCommon': 122575003648,
 'trailingEps': 8.27,
 'forwardEps': 9.55973,
 'pegRatio': 2.57,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 9.579,
 'enterpriseToEbitda': 27.031,
 '52WeekChange': 0.39152706,
 'SandP52WeekChange': 0.26603174,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1770595200,
 'quoteType': 'EQUITY',
 'currentPrice': 292.68,
 'targetHighPrice': 400.0,
 'targetLowPrice': 215.0,
 'targetMeanPrice': 305.28094,
 'targetMedianPrice': 310.0,
 'recommendationMean': 1.91667,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 42,
 'totalCash': 68507000832,
 'totalCashPerShare': 4.664,
 'ebitda': 159975997440,
 'totalDebt': 84710998016,
 'quickRatio': 0.906,
 'currentRatio': 1.07,
 'totalRevenue': 451442016256,
 'debtToEquity': 79.548,
 'revenuePerShare': 30.534,
 'returnOnAssets': 0.26229,
 'returnOnEquity': 1.4147099,
 'grossProfits': 216070995968,
 'freeCashflow': 101090746368,
 'operatingCashflow': 140222005248,
 'earningsGrowth': 0.218,
 'revenueGrowth': 0.166,
 'grossMargins': 0.47862,
 'ebitdaMargins': 0.35437,
 'operatingMargins': 0.32275,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'POST',
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': -0.02732902,
 'postMarketPrice': 292.6,
 'postMarketChange': -0.07998657,
 'regularMarketChange': -0.57699585,
 'regularMarketDayRange': '290.23 - 293.88',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 44422768,
 'fiftyTwoWeekLowChange': 99.219986,
 'fiftyTwoWeekLowChangePercent': 0.5128708,
 'fiftyTwoWeekRange': '193.46 - 294.76',
 'fiftyTwoWeekHighChange': -2.080017,
 'fiftyTwoWeekHighChangePercent': -0.007056646,
 'fiftyTwoWeekChangePercent': 39.152706,
 'dividendDate': 1778716800,
 'earningsTimestamp': 1777579200,
 'earningsTimestampStart': 1785441600,
 'earningsTimestampEnd': 1785441600,
 'earningsCallTimestampStart': 1777582800,
 'earningsCallTimestampEnd': 1777582800,
 'isEarningsDateEstimate': True,
 'regularMarketChangePercent': -0.19675435,
 'regularMarketPrice': 292.68,
 'corporateActions': [{'header': 'Dividend',
   'message': 'AAPL announced a cash dividend of $0.27 with an ex-date of May. 11, 2026',
   'meta': {'eventType': 'DIVIDEND',
    'dateEpochMs': 1778472000000,
    'amount': '0.27'}}],
 'postMarketTime': 1778536453,
 'regularMarketTime': 1778529601,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'epsTrailingTwelveMonths': 8.27,
 'epsForward': 9.55973,
 'epsCurrentYear': 8.72294,
 'priceEpsCurrentYear': 33.552906,
 'fiftyDayAverageChange': 29.87738,
 'fiftyDayAverageChangePercent': 0.11368753,
 'twoHundredDayAverageChange': 35.661438,
 'twoHundredDayAverageChangePercent': 0.13875045,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.9 - Buy',
 'cryptoTradeable': False,
 'displayName': 'Apple',
 'trailingPegRatio': 2.5713}

In [2]:
from edgar import Company, set_identity
import pandas as pd
set_identity("jonathon steeves jonathan.qsteeves@gmail.com")

/home/steevesj/miniconda3/envs/finance/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
form4_filings

╭──────────────────────────────────────── Filings for Apple Inc. [320193] ────────────────────────────────────────╮
│                                                                                                                 │
│                                                                              Filing                             │
│    Form        Description                                                   Date         Accession Number      │
│  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────  │
│    4           Statement of changes in beneficial ownership                  2026-05-08   0001140361-26-0202…   │
│    4           Statement of changes in beneficial ownership                  2026-04-27   0001140361-26-0171…   │
│    4           Statement of changes in beneficial ownership                  2026-04-17   0001140361-26-0154…   │
│    4           Statement of changes in beneficial ownership                  2026-04-17   0001140361-26-0154…   │
│    4           Statement of changes in beneficial ownership                  2026-04-03   0001140361-26-0131…   │
│    4           Statement of changes in beneficial ownership                  2026-04-03   0001140361-26-0131…   │
│    4           Statement of changes in beneficial ownership                  2026-04-03   0001140361-26-0131…   │
│    4           Statement of changes in beneficial ownership                  2026-03-17   0001780525-26-0000…   │
│    4           Statement of changes in beneficial ownership                  2026-02-26   0001059235-26-0000…   │
│    4           Statement of changes in beneficial ownership                  2026-02-26   0001216519-26-0000…   │
│                                                                                                                 │
╰─────────────── Company filings between 2026-02-26 and 2026-05-08 • filings.docs for usage guide ────────────────╯

In [9]:
company = Company("AAPL")
# print(company)

form4_filings = company.get_filings(form="4").head(10)
# print(form4_filings)

dataframe = None

for f in form4_filings:
    form4 = f.obj().to_dataframe()
    if dataframe is None:
        dataframe = form4
    else:
        dataframe = pd.concat([dataframe, form4], ignore_index=True)

dataframe.head(10)

/tmp/ipykernel_45584/3721976751.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dataframe = pd.concat([dataframe, form4], ignore_index=True)
/tmp/ipykernel_45584/3721976751.py:14: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  dataframe = pd.concat([dataframe, form4], ignore_index=True)

,Transaction Type,Code,Description,Shares,Price,Value,Date,Form,Issuer,Ticker,Insider,Position,Remaining Shares
0,Sale,S,Open Market Sale,149527,284.57,42550898.39,2026-05-06,Form 4,Apple Inc.,AAPL,Arthur D Levinson,Director,3819576
1,Sale,S,Open Market Sale,100473,285.04,28638823.92,2026-05-06,Form 4,Apple Inc.,AAPL,Arthur D Levinson,Director,3819576
2,Gift,G,Gift,5000,0.00,NaN,2026-05-06,Form 4,Apple Inc.,AAPL,Arthur D Levinson,Director,3819576
3,Sale,S,Open Market Sale,1534,275.00,421850.00,2026-04-23,Form 4,Apple Inc.,AAPL,Kevan Parekh,"Senior Vice President, CFO",13366
4,Exercise,M,Option Exercise,1717,NaN,NaN,2026-04-15,Form 4,Apple Inc.,AAPL,Ben Borders,Principal Accounting Officer,39987
5,Tax,F,Tax Withholding,892,266.43,237655.56,2026-04-15,Form 4,Apple Inc.,AAPL,Ben Borders,Principal Accounting Officer,39987
6,Derivative_Sale,M,Option Exercise (Common Stock),540,NaN,NaN,2026-04-15,Form 4,Apple Inc.,AAPL,Ben Borders,Principal Accounting Officer,39987
7,Derivative_Sale,M,Option Exercise (Common Stock),475,NaN,NaN,2026-04-15,Form 4,Apple Inc.,AAPL,Ben Borders,Principal Accounting Officer,39987
8,Derivative_Sale,M,Option Exercise (Common Stock),371,NaN,NaN,2026-04-15,Form 4,Apple Inc.,AAPL,Ben Borders,Principal Accounting Officer,39987
9,Derivative_Sale,M,Option Exercise (Common Stock),331,NaN,NaN,2026-04-15,Form 4,Apple Inc.,AAPL,Ben Borders,Principal Accounting Officer,39987

In [28]:
form4.to_dataframe()

,Transaction Type,Code,Description,Shares,Price,Value,Date,Form,Issuer,Ticker,Insider,Position,Remaining Shares
0,Sale,S,Open Market Sale,149527,284.57,42550898.39,2026-05-06,Form 4,Apple Inc.,AAPL,Arthur D Levinson,Director,3819576
1,Sale,S,Open Market Sale,100473,285.04,28638823.92,2026-05-06,Form 4,Apple Inc.,AAPL,Arthur D Levinson,Director,3819576
2,Gift,G,Gift,5000,0.00,NaN,2026-05-06,Form 4,Apple Inc.,AAPL,Arthur D Levinson,Director,3819576

In [12]:
insider = company.get_filings(form="4")
insider[0]

╭───────────────────── Form 4 Apple Inc. [320193]  ─────────────────────╮
│                                                                       │
│   Accession Number       Filing Date   Period of Report   Documents   │
│  ───────────────────────────────────────────────────────────────────  │
│   0001140361-26-020298   2026-05-08    2026-05-06         1           │
│                                                                       │
╰─ Statement of changes in beneficial ownership • filing.docs for usage─╯