# Historical Stock Market Data
Retrieve daily OHLCV (Open, High, Low, Close, Volume) data using pandas-datareader.

In [16]:
import pandas as pd
import yfinance as yf
from datetime import datetime

In [17]:
ticker = "AAPL"
start = datetime(2021, 1, 1)
end = datetime(2025, 12, 31)

In [ ]:
df = yf.download(
                tickers=ticker, 
                 interval="1d",
                 start=start, 
                 end=end, 
                 group_by="ticker", 
                 multi_level_index=False)

df.head()

[*********************100%***********************]  2 of 2 completed

Ticker            MSFT                                                \
Price             Open        High         Low       Close    Volume
Date
2021-01-04  213.040117  213.490075  205.649339  208.406525  37130100
2021-01-05  207.994898  209.201175  206.501427  208.607605  23823000
2021-01-06  203.121911  207.257690  202.901724  203.198502  35930700
2021-01-07  204.912170  209.986152  204.596255  208.980927  27694500
2021-01-08  209.354326  211.173309  207.774697  210.254242  22956200

Ticker            AAPL
Price             Open        High         Low       Close     Volume
Date
2021-01-04  129.853854  129.941379  123.279466  125.856705  143301900
2021-01-05  125.350965  128.122717  124.903590  127.412750   97664900
2021-01-06  124.213113  127.451681  122.909903  123.123863  155088000
2021-01-07  124.835528  128.015745  124.349256  127.325233  109578200
2021-01-08  128.793781  128.988301  126.654191  128.424225  105158200

In [33]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1254 entries, 2021-01-04 to 2025-12-30
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (MSFT, Open)    1254 non-null   float64
 1   (MSFT, High)    1254 non-null   float64
 2   (MSFT, Low)     1254 non-null   float64
 3   (MSFT, Close)   1254 non-null   float64
 4   (MSFT, Volume)  1254 non-null   int64
 5   (AAPL, Open)    1254 non-null   float64
 6   (AAPL, High)    1254 non-null   float64
 7   (AAPL, Low)     1254 non-null   float64
 8   (AAPL, Close)   1254 non-null   float64
 9   (AAPL, Volume)  1254 non-null   int64
dtypes: float64(8), int64(2)
memory usage: 107.8 KB

Ticker         MSFT                                                       \
Price          Open         High          Low        Close        Volume
count   1254.000000  1254.000000  1254.000000  1254.000000  1.254000e+03
mean     341.763804   344.885671   338.492568   341.831311  2.554321e+07
std       89.244480    89.495184    88.744261    89.125851  1.009796e+07
min      203.121911   205.362116   202.901724   203.198502  5.855900e+06
25%      263.498245   267.385536   260.272998   264.165642  1.891820e+07
50%      323.706213   326.264448   320.412414   323.169479  2.319270e+07
75%      413.734709   416.870751   410.137225   413.133728  2.949325e+07
max      552.023241   552.242002   538.530652   539.825256  9.042890e+07

Ticker         AAPL
Price          Open         High          Low        Close        Volume
count   1254.000000  1254.000000  1254.000000  1254.000000  1.254000e+03
mean     179.120713   181.064906   177.356837   179.299864  6.984941e+07
std       39.935068    40.211522    39.699827    39.986085  2.995081e+07
min      115.934688   117.269072   113.188029   113.334129  1.791060e+07
25%      145.769789   147.605371   144.506383   145.947102  4.839515e+07
50%      171.351155   173.015453   169.631075   171.515808  6.313855e+07
75%      209.917580   212.495536   207.742076   210.447929  8.455132e+07
max      285.932471   288.350192   283.035157   285.922455  3.186799e+08

In [34]:
ticker = yf.Ticker("MSFT")
expiration = ticker.options

In [38]:
ticker.option_chain(expiration[0])

Options(calls=         contractSymbol             lastTradeDate  strike  lastPrice    bid  \
0   MSFT260401C00330000 2026-03-31 19:44:26+00:00   330.0      41.60  39.60
1   MSFT260401C00337500 2026-03-30 13:30:03+00:00   337.5      21.95  31.85
2   MSFT260401C00340000 2026-03-31 19:25:01+00:00   340.0      31.30  29.50
3   MSFT260401C00342500 2026-03-31 18:45:57+00:00   342.5      27.42  26.70
4   MSFT260401C00345000 2026-03-31 19:31:10+00:00   345.0      26.28  24.65
5   MSFT260401C00347500 2026-03-27 19:34:05+00:00   347.5      11.90  22.10
6   MSFT260401C00350000 2026-03-31 19:46:30+00:00   350.0      20.40  19.50
7   MSFT260401C00352500 2026-03-31 13:32:08+00:00   352.5      18.55  17.10
8   MSFT260401C00355000 2026-03-31 19:43:19+00:00   355.0      16.06  14.15
9   MSFT260401C00357500 2026-03-31 19:20:29+00:00   357.5      13.83  11.90
10  MSFT260401C00360000 2026-03-31 19:56:24+00:00   360.0      10.30   9.85
11  MSFT260401C00362500 2026-03-31 19:48:00+00:00   362.5       9.30   7.80
12  MSFT260401C00365000 2026-03-31 19:53:38+00:00   365.0       5.85   5.85
13  MSFT260401C00367500 2026-03-31 19:59:47+00:00   367.5       4.00   4.00
14  MSFT260401C00370000 2026-03-31 19:59:34+00:00   370.0       2.65   2.59
15  MSFT260401C00372500 2026-03-31 19:59:37+00:00   372.5       1.55   1.50
16  MSFT260401C00375000 2026-03-31 19:59:46+00:00   375.0       0.83   0.77
17  MSFT260401C00377500 2026-03-31 19:59:52+00:00   377.5       0.40   0.35
18  MSFT260401C00380000 2026-03-31 19:59:50+00:00   380.0       0.19   0.16
19  MSFT260401C00382500 2026-03-31 19:59:33+00:00   382.5       0.07   0.06
20  MSFT260401C00385000 2026-03-31 19:59:34+00:00   385.0       0.03   0.02
21  MSFT260401C00387500 2026-03-31 19:52:58+00:00   387.5       0.02   0.01
22  MSFT260401C00390000 2026-03-31 19:59:30+00:00   390.0       0.01   0.00
23  MSFT260401C00392500 2026-03-31 19:56:48+00:00   392.5       0.01   0.00
24  MSFT260401C00395000 2026-03-31 19:40:02+00:00   395.0       0.01   0.00
25  MSFT260401C00397500 2026-03-31 19:18:56+00:00   397.5       0.01   0.00
26  MSFT260401C00400000 2026-03-31 19:46:28+00:00   400.0       0.02   0.00
27  MSFT260401C00402500 2026-03-31 19:39:32+00:00   402.5       0.01   0.00
28  MSFT260401C00405000 2026-03-31 16:49:37+00:00   405.0       0.01   0.00
29  MSFT260401C00407500 2026-03-31 19:45:57+00:00   407.5       0.01   0.00
30  MSFT260401C00410000 2026-03-31 18:47:38+00:00   410.0       0.06   0.00
31  MSFT260401C00412500 2026-03-30 19:29:14+00:00   412.5       0.01   0.00
32  MSFT260401C00415000 2026-03-31 19:17:05+00:00   415.0       0.01   0.00
33  MSFT260401C00420000 2026-03-31 19:46:28+00:00   420.0       0.01   0.00
34  MSFT260401C00425000 2026-03-24 17:24:05+00:00   425.0       0.05   0.00
35  MSFT260401C00430000 2026-03-31 16:38:23+00:00   430.0       0.01   0.00
36  MSFT260401C00435000 2026-03-18 15:23:43+00:00   435.0       0.37   0.00
37  MSFT260401C00440000 2026-03-30 17:35:58+00:00   440.0       0.01   0.00
38  MSFT260401C00445000 2026-03-31 19:40:30+00:00   445.0       0.01   0.00
39  MSFT260401C00455000 2026-03-25 13:36:57+00:00   455.0       0.10   0.00
40  MSFT260401C00465000 2026-03-24 18:29:21+00:00   465.0       0.06   0.00
41  MSFT260401C00475000 2026-03-30 14:32:46+00:00   475.0       0.01   0.00

      ask     change  percentChange   volume  openInterest  impliedVolatility  \
0   41.95  13.989998      50.670036    123.0           246           1.382816
1   34.45   0.000000       0.000000      1.0            16           1.106450
2   31.75  11.799999      60.512814     28.0           126           1.023442
3   29.45   9.920000      56.685715     27.0            29           0.928712
4   26.85  10.830001      70.097100      3.0            74           0.931641
5   24.45   0.000000       0.000000     25.0            25           0.866212
6   21.80   9.849999      93.364920     73.0           176           0.747073
7   19.20  10.549999     131.874980     18.0           283           0.673831
8   16.65   9.809999     156.959990    411.0           612           0.503911
9   13.25   9.180000     197.419370    230.0           420           0.551274
10  10.80   6.930000     205.637990   2033.0          1547           0.482915
11   9.45   6.970000     299.141630   1756.0           851           0.606938
12   6.30   4.310000     279.870150  12282.0          2058           0.396246
13   4.40   3.040000     316.666660  12529.0          1191           0.372565
14   2.75   2.030000     327.419430  17907.0          2610           0.344733
15   1.56   1.150000     287.500030  12506.0          1641           0.329841
16   0.85   0.580000     232.000000  11850.0          1797           0.331061
17   0.42   0.230000     135.294110   3340.0          1026           0.331550
18   0.19   0.090000      90.000000  12199.0          2847           0.333014
19   0.09  -0.010000     -12.499997   1688.0           720           0.342780
20   0.05  -0.030000     -50.000000   3721.0          1352           0.361335
21   0.03  -0.040000     -66.666670    845.0           374           0.382819
22   0.02  -0.030000     -75.000000    673.0           870           0.410162
23   0.02  -0.010000     -50.000000     98.0           235           0.453130
24   0.01   0.000000       0.000000    206.0           392           0.460943
25   0.08  -0.020000     -66.666670     14.0           130           0.585942
26   0.01   0.010000     100.000000    101.0           838           0.500005
27   0.01   0.000000       0.000000      1.0            64           0.546880
28   0.02  -0.020000     -66.666670      3.0           144           0.617191
29   0.03   0.000000       0.000000    198.0           168           0.679691
30   0.12   0.050000     499.999880      2.0           206           0.843752
31   0.21   0.000000       0.000000      3.0            72           0.955079
32   0.01   0.000000       0.000000      6.0            81           0.718753
33   0.01   0.000000       0.000000      2.0            86           0.781252
34   0.01   0.000000       0.000000     75.0            98           0.843752
35   0.01   0.000000       0.000000      4.0            46           0.906251
36   0.01   0.000000       0.000000      NaN             1           0.968750
37   0.01   0.000000       0.000000      1.0             3           1.062505
38   0.01  -0.140000     -93.333330     12.0            12           1.125004
39   0.01   0.000000       0.000000      1.0             3           1.250004
40   0.01   0.000000       0.000000      NaN             2           1.343753
41   0.01   0.000000       0.000000      1.0             2           1.468753

    inTheMoney contractSize currency
0         True      REGULAR      USD
1         True      REGULAR      USD
2         True      REGULAR      USD
3         True      REGULAR      USD
4         True      REGULAR      USD
5         True      REGULAR      USD
6         True      REGULAR      USD
7         True      REGULAR      USD
8         True      REGULAR      USD
9         True      REGULAR      USD
10        True      REGULAR      USD
11        True      REGULAR      USD
12        True      REGULAR      USD
13        True      REGULAR      USD
14        True      REGULAR      USD
15       False      REGULAR      USD
16       False      REGULAR      USD
17       False      REGULAR      USD
18       False      REGULAR      USD
19       False      REGULAR      USD
20       False      REGULAR      USD
21       False      REGULAR      USD
22       False      REGULAR      USD
23       False      REGULAR      USD
24       False      REGULAR      USD
25       False      REGULAR      USD
26       False      REGULAR      USD
27       False      REGULAR      USD
28       False      REGULAR      USD
29       False      REGULAR      USD
30       False      REGULAR      USD
31       False      REGULAR      USD
32       False      REGULAR      USD
33       False      REGULAR      USD
34       False      REGULAR      USD
35       False      REGULAR      USD
36       False      REGULAR      USD
37       False      REGULAR      USD
38       False      REGULAR      USD
39       False      REGULAR      USD
40       False      REGULAR      USD
41       False      REGULAR      USD  , puts=         contractSymbol             lastTradeDate  strike  lastPrice    bid  \
0   MSFT260401P00330000 2026-03-31 17:23:53+00:00   330.0       0.01   0.00
1   MSFT260401P00335000 2026-03-31 19:32:52+00:00   335.0       0.01   0.00
2   MSFT260401P00337500 2026-03-31 19:40:47+00:00   337.5       0.01   0.00
3   MSFT260401P00340000 2026-03-31 19:35:13+00:00   340.0       0.01   0.00
4   MSFT260401P00342500 2026-03-31 19:40:46+00:00   342.5       0.01   0.00
5   MSFT260401P00345000 2026-03-31 19:59:23+00:00   345.0       0.01   0.00
6   MSFT260401P00347500 2026-03-31 19:55:41+00:00   347.5       0.01   0.00
7   MSFT260401P00350000 2026-03-31 19:59:23+00:00   350.0       0.02   0.01
8   MSFT260401P00352500 2026-03-31 19:59:26+00:00   352.5       0.03   0.01
9   MSFT260401P00355000 2026-03-31 19:56:30+00:00   355.0       0.05   0.03
10  MSFT260401P00357500 2026-03-31 19:59:30+00:00   357.5       0.10   0.06
11  MSFT260401P00360000 2026-03-31 19:59:47+00:00   360.0       0.22   0.19
12  MSFT260401P00362500 2026-03-31 19:59:56+00:00   362.5       0.42   0.40
13  MSFT260401P00365000 2026-03-31 19:58:53+00:00   365.0       0.83   0.79
14  MSFT260401P00367500 2026-03-31 19:59:44+00:00   367.5       1.48   1.41
15  MSFT260401P00370000 2026-03-31 19:59:50+00:00   370.0       2.41   2.36
16  MSFT260401P00372500 2026-03-31 19:53:04+00:00   372.5       3.79   3.60
17  MSFT260401P00375000 2026-03-31 19:54:23+00:00   375.0       5.15   5.30
18  MSFT260401P00377500 2026-03-31 19:54:40+00:00   377.5       6.25   6.30
19  MSFT260401P00380000 2026-03-31 19:53:13+00:00   380.0       9.05   8.70
20  MSFT260401P00382500 2026-03-31 18:09:32+00:00   382.5      13.37  11.45
21  MSFT260401P00385000 2026-03-31 18:19:03+00:00   385.0      12.50  13.10
22  MSFT260401P00387500 2026-03-30 16:07:23+00:00   387.5      24.00  15.60
23  MSFT260401P00390000 2026-03-31 19:16:48+00:00   390.0      19.00  18.40
24  MSFT260401P00392500 2026-03-27 19:34:08+00:00   392.5      35.20  20.60
25  MSFT260401P00395000 2026-03-30 13:30:03+00:00   395.0      35.90  23.10
26  MSFT260401P00400000 2026-03-31 19:55:39+00:00   400.0      29.80  28.40
27  MSFT260401P00405000 2026-03-30 18:56:08+00:00   405.0      48.01  33.10
28  MSFT260401P00410000 2026-03-30 13:57:53+00:00   410.0      49.52  38.10
29  MSFT260401P00415000 2026-03-18 14:58:59+00:00   415.0      21.06  43.10
30  MSFT260401P00420000 2026-03-18 14:47:38+00:00   420.0      25.10  48.10
31  MSFT260401P00445000 2026-03-19 13:41:53+00:00   445.0      53.95  73.10

      ask     change  percentChange   volume  openInterest  impliedVolatility  \
0    0.50  -0.120000     -92.307690     56.0           279           1.167973
1    0.02  -0.150000     -93.749990    311.0           165           0.687503
2    0.02  -0.210000     -95.454544    195.0           287           0.640629
3    0.34  -0.290000     -96.666670   1110.0           553           0.849611
4    0.01  -0.390000     -97.500000    775.0           745           0.515630
5    0.01  -0.540000     -98.181820    947.0          2483           0.500005
6    0.01  -0.810000     -98.780490    943.0           704           0.453130
7    0.03  -1.110000     -98.230090   2225.0          1793           0.460943
8    0.04  -1.590000     -98.148150   4731.0           710           0.425787
9    0.07  -2.210000     -97.787610   3464.0          1350           0.404303
10   0.13  -3.150000     -96.923080   3659.0           862           0.387701
11   0.22  -4.170000     -94.988620  19112.0          1098           0.363288
12   0.47  -5.450000     -92.844980   7408.0          1308           0.361823
13   0.87  -6.620000     -88.859060  10283.0          1033           0.352301
14   1.51  -9.389999     -86.384544   6158.0           286           0.341803
15   2.50 -11.290000     -82.408760   5198.0           371           0.334479
16   4.00 -11.240000     -74.783770    651.0           160           0.344977
17   5.90 -10.920000     -67.952705    139.0           391           0.367682
18   8.10  -9.500000     -60.317460     85.0           175           0.406988
19  10.80 -11.780000     -56.553047     53.0           168           0.531743
20  13.30  -7.890000     -37.111950      2.0            41           0.613773
21  15.45 -13.070000     -51.114590    132.0            56           0.605961
22  18.60   0.000000       0.000000      1.0             0           0.837160
23  20.50 -12.450001     -39.586647     12.0             7           0.759768
24  23.55   0.000000       0.000000      4.0             0           0.976563
25  25.45   0.000000       0.000000      1.0             0           0.875978
26  30.40 -11.150002     -27.228330     10.0             0           0.982422
27  35.55   0.000000       0.000000      1.0             0           1.160160
28  40.45   0.000000       0.000000      1.0             0           1.238285
29  45.80   0.000000       0.000000      NaN             0           1.491213
30  50.55   0.000000       0.000000      NaN             0           1.506838
31  75.90   0.000000       0.000000      NaN             0           2.192387

    inTheMoney contractSize currency
0        False      REGULAR      USD
1        False      REGULAR      USD
2        False      REGULAR      USD
3        False      REGULAR      USD
4        False      REGULAR      USD
5        False      REGULAR      USD
6        False      REGULAR      USD
7        False      REGULAR      USD
8        False      REGULAR      USD
9        False      REGULAR      USD
10       False      REGULAR      USD
11       False      REGULAR      USD
12       False      REGULAR      USD
13       False      REGULAR      USD
14       False      REGULAR      USD
15       False      REGULAR      USD
16        True      REGULAR      USD
17        True      REGULAR      USD
18        True      REGULAR      USD
19        True      REGULAR      USD
20        True      REGULAR      USD
21        True      REGULAR      USD
22        True      REGULAR      USD
23        True      REGULAR      USD
24        True      REGULAR      USD
25        True      REGULAR      USD
26        True      REGULAR      USD
27        True      REGULAR      USD
28        True      REGULAR      USD
29        True      REGULAR      USD
30        True      REGULAR      USD
31        True      REGULAR      USD  , underlying={'language': 'en-US', 'region': 'US', 'quoteType': 'EQUITY', 'typeDisp': 'Equity', 'quoteSourceName': 'Nasdaq Real Time Price', 'triggerable': True, 'customPriceAlertConfidence': 'HIGH', 'hasPrePostMarketData': True, 'currency': 'USD', 'firstTradeDateMilliseconds': 511108200000, 'priceHint': 2, 'postMarketChangePercent': 0.76451, 'postMarketPrice': 373.0, 'postMarketChange': 2.8299866, 'regularMarketChange': 11.21, 'regularMarketDayHigh': 372.9, 'regularMarketDayRange': '363.07 - 372.9', 'regularMarketDayLow': 363.07, 'regularMarketVolume': 44146894, 'regularMarketPreviousClose': 358.96, 'bid': 369.85, 'ask': 370.39, 'bidSize': 2, 'askSize': 1, 'fullExchangeName': 'NasdaqGS', 'epsTrailingTwelveMonths': 15.97, 'epsForward': 18.85049, 'epsCurrentYear': 16.7292, 'priceEpsCurrentYear': 22.12718, 'sharesOutstanding': 7425629076, 'bookValue': 52.615, 'fiftyDayAverage': 408.5164, 'fiftyDayAverageChange': -38.346375, 'fiftyDayAverageChangePercent': -0.093867406, 'twoHundredDayAverage': 478.5149, 'twoHundredDayAverageChange': -108.34488, 'twoHundredDayAverageChangePercent': -0.22641903, 'marketCap': 2751243485184, 'forwardPE': 19.637156, 'priceToBook': 7.035446, 'sourceInterval': 15, 'exchangeDataDelayedBy': 0, 'averageAnalystRating': '1.3 - Strong Buy', 'exchange': 'NMS', 'messageBoardId': 'finmb_21835', 'exchangeTimezoneName': 'America/New_York', 'exchangeTimezoneShortName': 'EDT', 'gmtOffSetMilliseconds': -14400000, 'market': 'us_market', 'esgPopulated': False, 'marketState': 'POSTPOST', 'shortName': 'Microsoft Corporation', 'longName': 'Microsoft Corporation', 'tradeable': False, 'cryptoTradeable': False, 'corporateActions': [], 'postMarketTime': 1775001598, 'regularMarketTime': 1774987201, 'regularMarketChangePercent': 3.12292, 'regularMarketPrice': 370.17, 'financialCurrency': 'USD', 'regularMarketOpen': 364.63, 'averageDailyVolume3Month': 36406065, 'averageDailyVolume10Day': 35124070, 'fiftyTwoWeekLowChange': 25.380005, 'fiftyTwoWeekLowChangePercent': 0.07361004, 'fiftyTwoWeekRange': '344.79 - 555.45', 'fiftyTwoWeekHighChange': -185.28, 'fiftyTwoWeekHighChangePercent': -0.33356738, 'fiftyTwoWeekLow': 344.79, 'fiftyTwoWeekHigh': 555.45, 'fiftyTwoWeekChangePercent': -6.06584, 'dividendDate': 1781136000, 'earningsTimestamp': 1769634000, 'earningsTimestampStart': 1777492800, 'earningsTimestampEnd': 1777492800, 'earningsCallTimestampStart': 1769639400, 'earningsCallTimestampEnd': 1769639400, 'isEarningsDateEstimate': True, 'trailingAnnualDividendRate': 3.48, 'trailingPE': 23.179087, 'dividendRate': 3.64, 'trailingAnnualDividendYield': 0.009694674, 'dividendYield': 1.01, 'displayName': 'Microsoft', 'symbol': 'MSFT'})